algoritmo "semnome"
// Função :
// Autor :
// Data : 06/04/2020
// Seção de Declarações
var
numero : inteiro

inicio
// Seção de Comandos
escreva(" digite o numero : ")
leia(numero)

se ( numero > 0 ) entao
              escreva ( " numero positivo")
senao
     se ( numero < 0) entao
              escreva ( "numero negativo")
     senao
              escreva ( "numero nulo")
     fimse
fimse

fimalgoritmo
