algoritmo "soma dois numeros"
// Função : Somar dois números digitados
// Autor : Igor Lima Mendes
// Data : 06/04/2020
// Seção de Declarações 
var
numero1, numero2, soma: inteiro
nome: literal
inicio
escreva("Olá! Informe o seu nome: ")
leia(nome)
escreva(nome, ", Informe o 1º número: ")
leia(numero1)
escreva("Agora, ", nome, ", informe o 2º número: ")
leia(numero2)
escreval("")

soma := numero1 + numero2

escreval("Resultado: ", soma)
fimalgoritmo
